## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/prod"
  to = "https://8x74wn1vt2.execute-api.us-east-1.amazonaws.com/prod"
  status = 200
  force = true # COMMENT: ensure that we always redirect
